import os
import time
def carga():
    d=0
    g=4
    while d<g:
        print("    🔴")
        print(" 🔴    🔴")
        print(" 🔴    🔴")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴 ")
        print(" 🔴    🔴")
        print(" 🔴    🔴")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print(" 🔴     ")
        print(" 🔴    🔴")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print(" 🔴    🔴")
        print(" 🔴     ")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print(" 🔴    🔴")
        print(" 🔴    🔴")
        print("   🔴 ")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print(" 🔴    🔴")
        print(" 🔴    🔴")
        print("    🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print(" 🔴    🔴")
        print("       🔴")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        print("   🔴🔴")
        print("       🔴")
        print(" 🔴    🔴")
        print("   🔴🔴")
        time.sleep(.2)
        os.system ("cls")
        d+=1